version: '3.9'

volumes:
  db:

services:
  postgresql:
    image: postgres:15.4
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: backend
    container_name: backend
    env_file: ./backend/.env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    environment:
      VITE_BASE_API_URL: backend:3000
    ports:
      - 8080:80
    restart: always
    depends_on:
      backend:
        condition: service_started
        