export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN';
export const REFRESH_TOKEN_COOKIE = 'refresh_token';
export const COOKIE_SECRET = 'COOKIE_SECRET';
export const FT_CLIENT_ID = 'FT_CLIENT_ID';
export const FT_CLIENT_SECRET = 'FT_CLIENT_SECRET';
export const FT_CALLBACK_URL = 'FT_CALLBACK_URL';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';
export const FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID';
export const FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET';
export const FACEBOOK_CALLBACK_URL = 'FACEBOOK_CALLBACK_URL';

// AWS
export const AWS_REGION = 'AWS_REGION';
export const AWS_BUCKET_NAME = 'AWS_BUCKET_NAME';
export const AWS_TMP_BUCKET_NAME = 'AWS_TMP_BUCKET_NAME';
export const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';
export const AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';
export const AWS_EXPIRES_IN = 60;

// REGEX
export const PASSWORD_REGEX =
  /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^*-]).{8,}$/;
